// <auto-generated />
using System;
using DataLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DataLayer.Migrations
{
    [DbContext(typeof(ChessContext))]
    [Migration("20250815012514_puzzle_3_relations")]
    partial class puzzle_3_relations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DataLayer.Entities.Chess.ChessGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BlackId")
                        .HasColumnType("integer");

                    b.Property<string>("BlackUsername")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GameType")
                        .HasColumnType("integer");

                    b.Property<int>("Result")
                        .HasColumnType("integer");

                    b.Property<int>("WhiteId")
                        .HasColumnType("integer");

                    b.Property<string>("WhiteUsername")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BlackId");

                    b.HasIndex("WhiteId");

                    b.ToTable("ChessGames");
                });

            modelBuilder.Entity("DataLayer.Entities.Chess.Move", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChessGameId")
                        .HasColumnType("integer");

                    b.Property<string>("FEN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MoveString")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ChessGameId");

                    b.ToTable("Moves");
                });

            modelBuilder.Entity("DataLayer.Entities.Chess.Puzzle", b =>
                {
                    b.Property<string>("PuzzleId")
                        .HasColumnType("text");

                    b.Property<string>("FEN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GameUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Moves")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NbPlays")
                        .HasColumnType("integer");

                    b.Property<string>("OpeningTags")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Popularity")
                        .HasColumnType("integer");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<int>("RatingDeviation")
                        .HasColumnType("integer");

                    b.Property<string>("Themes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PuzzleId");

                    b.ToTable("Puzzles", (string)null);
                });

            modelBuilder.Entity("DataLayer.Entities.Chess.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tags", (string)null);
                });

            modelBuilder.Entity("DataLayer.Entities.Relations.PuzzleTag", b =>
                {
                    b.Property<string>("PuzzleId")
                        .HasColumnType("text");

                    b.Property<int>("TagId")
                        .HasColumnType("integer");

                    b.HasKey("PuzzleId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("PuzzleTag", (string)null);
                });

            modelBuilder.Entity("DataLayer.Entities.Users.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DataLayer.Entities.Chess.ChessGame", b =>
                {
                    b.HasOne("DataLayer.Entities.Users.User", "BlackPlayer")
                        .WithMany("BlackGames")
                        .HasForeignKey("BlackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataLayer.Entities.Users.User", "WhitePlayer")
                        .WithMany("WhiteGames")
                        .HasForeignKey("WhiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BlackPlayer");

                    b.Navigation("WhitePlayer");
                });

            modelBuilder.Entity("DataLayer.Entities.Chess.Move", b =>
                {
                    b.HasOne("DataLayer.Entities.Chess.ChessGame", "ChessGame")
                        .WithMany("Moves")
                        .HasForeignKey("ChessGameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChessGame");
                });

            modelBuilder.Entity("DataLayer.Entities.Relations.PuzzleTag", b =>
                {
                    b.HasOne("DataLayer.Entities.Chess.Puzzle", "Puzzle")
                        .WithMany("PuzzleTags")
                        .HasForeignKey("PuzzleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataLayer.Entities.Chess.Tag", "Tag")
                        .WithMany("PuzzleTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Puzzle");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("DataLayer.Entities.Chess.ChessGame", b =>
                {
                    b.Navigation("Moves");
                });

            modelBuilder.Entity("DataLayer.Entities.Chess.Puzzle", b =>
                {
                    b.Navigation("PuzzleTags");
                });

            modelBuilder.Entity("DataLayer.Entities.Chess.Tag", b =>
                {
                    b.Navigation("PuzzleTags");
                });

            modelBuilder.Entity("DataLayer.Entities.Users.User", b =>
                {
                    b.Navigation("BlackGames");

                    b.Navigation("WhiteGames");
                });
#pragma warning restore 612, 618
        }
    }
}
