name: Backend Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run backend tests
        run: docker compose run backend dotnet test ./Testing/Testing.csproj
