name: Backend Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build and start all services
        run: docker compose up -d --build

      - name: Run backend tests
        run: docker compose exec backend dotnet test ./Testing/Testing.csproj

      - name: Shutdown services
        run: docker compose down

